### ISSUE TITLE
Build failed with exception

### ISSUE THREAD

**Issue by gisinator** [OpenFlutter/flutter_image_compress#69]
Hi,
I just upgraded to latest flutter stable 1.7.8hotfix3 and also to flutter_image_compress 0.6.3, now I get this when trying to build:

---

Initializing gradle...                                              1,0s
Resolving dependencies...                                           4,6s
Launching lib/main.dart on ANE LX1 in release mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_image_compress-0.6.2\android\src\main\kotlin\com\example\flutterimagecompress\FlutterImageCompressPlugin.kt: (11, 7): Redeclaration: FlutterImageCompressPlugin
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_image_compress-0.6.2\android\src\main\kotlin\com\example\flutterimagecompress\core\CompressFileHandler.kt: (15, 7): Redeclaration: CompressFileHandler
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_image_compress-0.6.2\android\src\main\kotlin\com\example\flutterimagecompress\core\CompressListHandler.kt: (17, 7): Redeclaration: CompressListHandler
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_image_compress-0.6.3\android\src\main\kotlin\com\example\flutterimagecompress\FlutterImageCompressPlugin.kt: (11, 7): Redeclaration: FlutterImageCompressPlugin
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_image_compress-0.6.3\android\src\main\kotlin\com\example\flutterimagecompress\FlutterImageCompressPlugin.kt: (25, 76): Type mismatch: inferred type is PluginRegistry.Registrar but Activity was expected
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_image_compress-0.6.3\android\src\main\kotlin\com\example\flutterimagecompress\FlutterImageCompressPlugin.kt: (26, 76): Type mismatch: inferred type is PluginRegistry.Registrar but Activity was expected
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_image_compress-0.6.3\android\src\main\kotlin\com\example\flutterimagecompress\core\CompressFileHandler.kt: (15, 7): Redeclaration: CompressFileHandler
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_image_compress-0.6.3\android\src\main\kotlin\com\example\flutterimagecompress\core\CompressListHandler.kt: (17, 7): Redeclaration: CompressListHandler

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_image_compress:compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s

---

Kotlin: 1.3.41

Any idea? :)

**Comment by gisinator** [comment]
Did a "flutter clean" command, now it works again. :)

**Comment by CaiJingLong** [comment]
So, this is an error of cache.
Thanks for issue.

**Comment by and301** [comment]
I got the same error but I just upgraded this flutter_image_compress 0.6.3 to 0.7.0, I just downgraded to the previous version  0.6.3 and that's it, it solved the error.

**Comment by CaiJingLong** [comment]
> I got the same error when I upgraded the flutter_image_compress from 0.6.3 to 0.7.0, to solve this, I just downgraded back to the previous version 0.6.3 and that's it, it solved the error.

Try running flutter clean and see if it solves your problem?

**Comment by sherphard33** [comment]
> Did a "flutter clean" command, now it works again. :)

Worked for me too, thanks
